// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, currency, created_at)
VALUES ($1, $2, $3)
RETURNING id, currency, created_at
`

type CreateAccountParams struct {
	ID        pgtype.UUID        `json:"id"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg *CreateAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.Currency, arg.CreatedAt)
	var i Account
	err := row.Scan(&i.ID, &i.Currency, &i.CreatedAt)
	return &i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, currency, created_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.Currency, &i.CreatedAt)
	return &i, err
}
