// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (id, actor, action, entity_type, entity_id, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor, action, entity_type, entity_id, payload, created_at
`

type CreateAuditLogParams struct {
	ID         pgtype.UUID        `json:"id"`
	Actor      string             `json:"actor"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg *CreateAuditLogParams) (*AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.Actor,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.CreatedAt,
	)
	return &i, err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT id, actor, action, entity_type, entity_id, payload, created_at FROM audit_log
WHERE
    ($1::text        IS NULL OR entity_type = $1)
    AND ($2::uuid        IS NULL OR entity_id   = $2)
    AND ($3::timestamptz IS NULL OR created_at  >= $3)
    AND ($4::timestamptz IS NULL OR created_at  <= $4)
    AND (created_at, id) < ($5, $6)
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type GetAuditLogsParams struct {
	Column1     string             `json:"column_1"`
	Column2     pgtype.UUID        `json:"column_2"`
	Column3     pgtype.Timestamptz `json:"column_3"`
	Column4     pgtype.Timestamptz `json:"column_4"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetAuditLogs(ctx context.Context, arg *GetAuditLogsParams) ([]*AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
