// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, transaction_id, account_id, direction, amount, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, account_id, direction, amount, created_at
`

type CreateEntryParams struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Direction     string             `json:"direction"`
	Amount        int64              `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg *CreateEntryParams) (*Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountID,
		arg.Direction,
		arg.Amount,
		arg.CreatedAt,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Direction,
		&i.Amount,
		&i.CreatedAt,
	)
	return &i, err
}

const getBalance = `-- name: GetBalance :one
SELECT (
    COALESCE(SUM(CASE WHEN direction = 'CREDIT' THEN amount ELSE 0 END), 0::BIGINT) -
    COALESCE(SUM(CASE WHEN direction = 'DEBIT'  THEN amount ELSE 0 END), 0::BIGINT)
)::BIGINT AS balance
FROM entries
WHERE account_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getEntriesByAccount = `-- name: GetEntriesByAccount :many
SELECT id, transaction_id, account_id, direction, amount, created_at FROM entries
WHERE account_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type GetEntriesByAccountParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.UUID        `json:"column_3"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) GetEntriesByAccount(ctx context.Context, arg *GetEntriesByAccountParams) ([]*Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByAccount,
		arg.AccountID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Direction,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByTransaction = `-- name: GetEntriesByTransaction :many
SELECT id, transaction_id, account_id, direction, amount, created_at FROM entries
WHERE transaction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetEntriesByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]*Entry, error) {
	rows, err := q.db.Query(ctx, getEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Direction,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
