// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, idempotency_key, amount, currency, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, idempotency_key, amount, currency, status, created_at
`

type CreateTransactionParams struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Amount         int64              `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg *CreateTransactionParams) (*Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.IdempotencyKey,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, idempotency_key, amount, currency, status, created_at FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (*Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, idempotency_key, amount, currency, status, created_at FROM transactions
WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (*Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}
